name: 'The code is analyzing from sonarcloud'
description: ' The code will analyze from sonarcloud.'
inputs:
  SonarCloud_Project_Key:  # path
    description: 'Sonarcloud Project_Key '
    required: true
    default: 'enespekdas_ms-ratings-web-master'
  SonarCloud_Organizaton_Name:  # path
      description: 'Sonarcloud Organization Name '
      required: true
      default: 'enespekdas'
  SONAR_TOKEN:  # path
      description: 'Sonarcloud get project token '
      required: true
      default: 'dd'
  GITHUB_TOKEN:  # path  
      description: 'Github get Token '
      required: true
      default: 'dd'
outputs:
  Result: 
    description: "Sonarcloud Result"
    value: "Sonarcloud Analyze finished."
runs:
  using: "composite"
  steps: 
    - name: Repository Files are downloading
      uses: actions/checkout@v2
    - run: pwd 
      shell: bash
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectKey=${{ inputs.SonarCloud_Project_Key }}
          -Dsonar.organization=${{ inputs.SonarCloud_Organizaton_Name }}
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}